/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/DetectionLogsScreen` | `/DetectionLogsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/EventLogsScreen` | `/EventLogsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ObservationLogScreen` | `/ObservationLogScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/QuestionnaireScreen` | `/QuestionnaireScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet1`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet2`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet3`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet4`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet5`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet6`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/DetectionLogsScreen` | `/DetectionLogsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/EventLogsScreen` | `/EventLogsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ObservationLogScreen` | `/ObservationLogScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/QuestionnaireScreen` | `/QuestionnaireScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/StyleSheets/StyleSheet1`; params?: Router.UnknownOutputParams; } | { pathname: `/StyleSheets/StyleSheet2`; params?: Router.UnknownOutputParams; } | { pathname: `/StyleSheets/StyleSheet3`; params?: Router.UnknownOutputParams; } | { pathname: `/StyleSheets/StyleSheet4`; params?: Router.UnknownOutputParams; } | { pathname: `/StyleSheets/StyleSheet5`; params?: Router.UnknownOutputParams; } | { pathname: `/StyleSheets/StyleSheet6`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/DetectionLogsScreen${`?${string}` | `#${string}` | ''}` | `/DetectionLogsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/EventLogsScreen${`?${string}` | `#${string}` | ''}` | `/EventLogsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ObservationLogScreen${`?${string}` | `#${string}` | ''}` | `/ObservationLogScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/QuestionnaireScreen${`?${string}` | `#${string}` | ''}` | `/QuestionnaireScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `/StyleSheets/StyleSheet1${`?${string}` | `#${string}` | ''}` | `/StyleSheets/StyleSheet2${`?${string}` | `#${string}` | ''}` | `/StyleSheets/StyleSheet3${`?${string}` | `#${string}` | ''}` | `/StyleSheets/StyleSheet4${`?${string}` | `#${string}` | ''}` | `/StyleSheets/StyleSheet5${`?${string}` | `#${string}` | ''}` | `/StyleSheets/StyleSheet6${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/DetectionLogsScreen` | `/DetectionLogsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/EventLogsScreen` | `/EventLogsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ObservationLogScreen` | `/ObservationLogScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/QuestionnaireScreen` | `/QuestionnaireScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet1`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet2`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet3`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet4`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet5`; params?: Router.UnknownInputParams; } | { pathname: `/StyleSheets/StyleSheet6`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
